package main

var siteMaps = []string{
	"https://islamqa.info/sitemaps/sitemap-fatawa-ar-1.xml",
	"https://islamqa.info/sitemaps/sitemap-article-ar-1.xml",
	// "https://islamqa.info/sitemaps/sitemap-book-ar-1.xml",
	// "https://islamqa.info/sitemaps/sitemap-old_category-ar-1.xml",
	// "https://islamqa.info/sitemaps/sitemap-file-ar-1.xml",
	// "https://islamqa.info/sitemaps/sitemap-subsite-ar-1.xml",
	"https://islamqa.info/sitemaps/sitemap-fatawa-bn-1.xml",
	// "https://islamqa.info/sitemaps/sitemap-old_category-bn-1.xml",
	// "https://islamqa.info/sitemaps/sitemap-file-bn-1.xml",
	// "https://islamqa.info/sitemaps/sitemap-subsite-bn-1.xml",
	"https://islamqa.info/sitemaps/sitemap-fatawa-en-1.xml",
	"https://islamqa.info/sitemaps/sitemap-article-en-1.xml",
	// "https://islamqa.info/sitemaps/sitemap-book-en-1.xml",
	// "https://islamqa.info/sitemaps/sitemap-old_category-en-1.xml",
	// "https://islamqa.info/sitemaps/sitemap-file-en-1.xml",
	// "https://islamqa.info/sitemaps/sitemap-subsite-en-1.xml",
	"https://islamqa.info/sitemaps/sitemap-fatawa-es-1.xml",
	"https://islamqa.info/sitemaps/sitemap-article-es-1.xml",
	// "https://islamqa.info/sitemaps/sitemap-book-es-1.xml",
	// "https://islamqa.info/sitemaps/sitemap-old_category-es-1.xml",
	// "https://islamqa.info/sitemaps/sitemap-file-es-1.xml",
	// "https://islamqa.info/sitemaps/sitemap-subsite-es-1.xml",
	"https://islamqa.info/sitemaps/sitemap-fatawa-fa-1.xml",
	// "https://islamqa.info/sitemaps/sitemap-book-fa-1.xml",
	// "https://islamqa.info/sitemaps/sitemap-old_category-fa-1.xml",
	// "https://islamqa.info/sitemaps/sitemap-file-fa-1.xml",
	// "https://islamqa.info/sitemaps/sitemap-subsite-fa-1.xml",
	"https://islamqa.info/sitemaps/sitemap-fatawa-fr-1.xml",
	"https://islamqa.info/sitemaps/sitemap-article-fr-1.xml",
	// "https://islamqa.info/sitemaps/sitemap-old_category-fr-1.xml",
	// "https://islamqa.info/sitemaps/sitemap-file-fr-1.xml",
	// "https://islamqa.info/sitemaps/sitemap-subsite-fr-1.xml",
	"https://islamqa.info/sitemaps/sitemap-fatawa-ge-1.xml",
	"https://islamqa.info/sitemaps/sitemap-article-ge-1.xml",
	// "https://islamqa.info/sitemaps/sitemap-book-ge-1.xml",
	// "https://islamqa.info/sitemaps/sitemap-old_category-ge-1.xml",
	// "https://islamqa.info/sitemaps/sitemap-file-ge-1.xml",
	// "https://islamqa.info/sitemaps/sitemap-subsite-ge-1.xml",
	"https://islamqa.info/sitemaps/sitemap-fatawa-hi-1.xml",
	// "https://islamqa.info/sitemaps/sitemap-old_category-hi-1.xml",
	// "https://islamqa.info/sitemaps/sitemap-file-hi-1.xml",
	// "https://islamqa.info/sitemaps/sitemap-subsite-hi-1.xml",
	"https://islamqa.info/sitemaps/sitemap-fatawa-id-1.xml",
	"https://islamqa.info/sitemaps/sitemap-article-id-1.xml",
	// "https://islamqa.info/sitemaps/sitemap-old_category-id-1.xml",
	// "https://islamqa.info/sitemaps/sitemap-file-id-1.xml",
	// "https://islamqa.info/sitemaps/sitemap-subsite-id-1.xml",
	"https://islamqa.info/sitemaps/sitemap-fatawa-pt-1.xml",
	// "https://islamqa.info/sitemaps/sitemap-old_category-pt-1.xml",
	// "https://islamqa.info/sitemaps/sitemap-file-pt-1.xml",
	// "https://islamqa.info/sitemaps/sitemap-subsite-pt-1.xml",
	"https://islamqa.info/sitemaps/sitemap-fatawa-ru-1.xml",
	// "https://islamqa.info/sitemaps/sitemap-book-ru-1.xml",
	// "https://islamqa.info/sitemaps/sitemap-old_category-ru-1.xml",
	// "https://islamqa.info/sitemaps/sitemap-file-ru-1.xml",
	// "https://islamqa.info/sitemaps/sitemap-subsite-ru-1.xml",
	"https://islamqa.info/sitemaps/sitemap-fatawa-tg-1.xml",
	"https://islamqa.info/sitemaps/sitemap-article-tg-1.xml",
	// "https://islamqa.info/sitemaps/sitemap-book-tg-1.xml",
	// "https://islamqa.info/sitemaps/sitemap-old_category-tg-1.xml",
	"https://islamqa.info/sitemaps/sitemap-fatawa-tr-1.xml",
	// "https://islamqa.info/sitemaps/sitemap-book-tr-1.xml",
	// "https://islamqa.info/sitemaps/sitemap-old_category-tr-1.xml",
	// "https://islamqa.info/sitemaps/sitemap-file-tr-1.xml",
	// "https://islamqa.info/sitemaps/sitemap-subsite-tr-1.xml",
	"https://islamqa.info/sitemaps/sitemap-fatawa-ug-1.xml",
	"https://islamqa.info/sitemaps/sitemap-article-ug-1.xml",
	// "https://islamqa.info/sitemaps/sitemap-old_category-ug-1.xml",
	// "https://islamqa.info/sitemaps/sitemap-file-ug-1.xml",
	// "https://islamqa.info/sitemaps/sitemap-subsite-ug-1.xml",
	"https://islamqa.info/sitemaps/sitemap-fatawa-ur-1.xml",
	"https://islamqa.info/sitemaps/sitemap-article-ur-1.xml",
	// "https://islamqa.info/sitemaps/sitemap-book-ur-1.xml",
	// "https://islamqa.info/sitemaps/sitemap-old_category-ur-1.xml",
	// "https://islamqa.info/sitemaps/sitemap-file-ur-1.xml",
	// "https://islamqa.info/sitemaps/sitemap-subsite-ur-1.xml",
	"https://islamqa.info/sitemaps/sitemap-fatawa-zh-1.xml",
	"https://islamqa.info/sitemaps/sitemap-article-zh-1.xml",
	// "https://islamqa.info/sitemaps/sitemap-old_category-zh-1.xml",
	// "https://islamqa.info/sitemaps/sitemap-file-zh-1.xml",
	// "https://islamqa.info/sitemaps/sitemap-subsite-zh-1.xml",
}
